var Patient_Response_Router = require("express").Router(),
                    moment = require("moment");

var  Response_Details =  require("../models/response_details");
var  Response_Master =  require("../models/response_master");
var  Patient_Master  =  require("../models/patieent_master");

/**
 * @api {post} api/Response API to send response from Patient
 * @apiGroup Response
 * @apiDescription This API is to sending response by user.
 * @apiParam {Number} [patientID=001] Will be sent along with post request when user is logged in else this post route can not be accessed by user
 * @apiParam {Number} response_id     Mandatory ID for sample form response.
 * @apiParam {String} response_text   Mandatory text for sample.
 * @apiParam {String} [response_date=2013-02-08] IN Format (2013-02-08  YYYY-MM-DD) Reponse Date will be auto generated by client browser but to test provide with some date.
 * @apiSampleRequest http://localhost:4000/api/Response
 */


Patient_Response_Router.route("/Response")
                        .post((req,res) => {
                            var tempPID = req.body.patientID;
                            var dateCreate = req.body.response_date;

                            console.log("outside promise" + tempPID)

                            if(req.body.response_id)
                             {
                                Response_Details.create(
                                    {
                                        response_id: req.body.response_id,
                                        response_text: req.body.response_text,
                                    }).then(newResponse => { 
                                        Response_Master.findOne(
                                            {where: {patient_id: tempPID}},
                                        ).then (o => {
                                            if (o) {
                                                console.log("Parsed body p id " + tempPID);
                                                o.updateAttributes({
                                                    response_id: newResponse.response_id,
                                                    created_on: moment(dateCreate).toDate(),
                                                });
                                            }
                                            else {
                                                Response_Master.create({
                                                    response_id: newResponse.response_id,
                                                    patient_id: tempPID,
                                                    created_on: moment(dateCreate).toDate()
                                                });
                                            }
                                        })
                                        res.status(200).json(newResponse);
                                    }).catch(error => {
                                        res.status(200).send("Error");
                                    }).catch(err => console.log(err))
                             }
                             else{
                                 res.status(500).send('Server Error  or Empty Post');
                             }
                        });

module.exports =  Patient_Response_Router;